In [3]:
import torch
from methods.clustering.faster_mix_k_means_pytorch import pairwise_distance
from project_utils.lorentz import pairwise_dist as lorentz_pairwise_dist
from project_utils.lorentz import pairwise_inner as lorentz_pairwise_inner

In [9]:
embeds = torch.randn(10, 512)
centers = torch.randn(5, 512)
pair_dist = pairwise_distance(embeds, centers)
dist2 = torch.matmul(embeds, centers.t())
hyp_pair_dist = lorentz_pairwise_dist(embeds, centers, 2) 

In [10]:
print(pair_dist.shape)
print(dist2.shape)
print(hyp_pair_dist.shape)


torch.Size([10, 5])
torch.Size([10, 5])
torch.Size([10, 5])


In [11]:
print(pair_dist)
print(dist2)

tensor([[1012.7142, 1023.2885,  989.1441, 1057.6973,  995.8853],
        [1068.1846,  971.4751, 1031.1577, 1067.6117, 1085.8468],
        [ 992.2310,  993.9666, 1010.7922,  958.0060,  971.3592],
        [1059.5291,  995.1831,  894.7130, 1066.6942, 1057.3076],
        [1044.4165,  980.5476,  969.7465, 1113.5642, 1017.2137],
        [1189.9812,  985.1036, 1032.6238, 1051.2634, 1079.8756],
        [1015.4780,  873.4585, 1013.3519, 1067.2152,  979.9601],
        [1213.7441, 1045.0063, 1086.8579, 1049.1482, 1095.7402],
        [1123.5165, 1035.3019, 1034.4357, 1037.2007, 1046.1222],
        [1134.2799, 1051.1781, 1027.2856, 1138.2362, 1128.4786]])
tensor([[ 29.3874, -25.6107, -14.6008, -13.9754,   8.1716],
        [ 19.3349,  17.9787, -17.9249,  -1.2499, -19.1265],
        [ 33.2585, -17.3201, -31.7953,  29.4998,  14.0641],
        [  6.3797, -11.1581,  33.0146, -18.0740, -22.1398],
        [ 11.1189,  -6.6574,  -7.3192, -44.3261,  -4.9099],
        [-35.1894,  17.5385, -12.2839,  13.2982, 

In [38]:
embed = torch.arange(0, 7).float().view(-1, 1)
center = torch.arange(-3, 4).float().view(-1, 1)
torch.sqrt(pairwise_distance(embed, center))
lorentz_pairwise_dist(embed, center, 11)

tensor([[0.9025, 0.7812, 0.5771, 0.0000, 0.5771, 0.7812, 0.9025],
        [1.4796, 1.3583, 1.1542, 0.5771, 0.0000, 0.2041, 0.3254],
        [1.6837, 1.5624, 1.3583, 0.7812, 0.2041, 0.0000, 0.1213],
        [1.8050, 1.6837, 1.4796, 0.9025, 0.3254, 0.1213, 0.0000],
        [1.8914, 1.7701, 1.5660, 0.9889, 0.4118, 0.2077, 0.0864],
        [1.9585, 1.8372, 1.6331, 1.0560, 0.4789, 0.2748, 0.1535],
        [2.0134, 1.8921, 1.6880, 1.1109, 0.5338, 0.3297, 0.2084]])